feat(proj0): finish task 2 - step through
```
$ pintos-debug
Copying tests/userprog/do-nothing to scratch partition...
squish-pty bochs -q
========================================================================
                       Bochs x86 Emulator 2.6.7
              Built from SVN snapshot on November 2, 2014
                  Compiled on Jan 15 2024 at 11:05:00
========================================================================
00000000000i[      ] reading configuration from bochsrc.txt
00000000000e[      ] bochsrc.txt:8: 'user_shortcut' will be replaced by new 'keyboard' option.
00000000000i[      ] Enabled gdbstub
00000000000i[      ] installing nogui module as the Bochs GUI
00000000000i[      ] using log file bochsout.txt
Waiting for gdb connection on port 45079
Connected to 127.0.0.1
PiLo hda1
Loading.............
Kernel command line: -q -f extract run do-nothing
##########
(gdb) b run_task
(gdb) c
##########
Pintos booting with 4,096 kB RAM...
383 pages available in kernel pool.
383 pages available in user pool.
Calibrating timer...  102,400 loops/s.
hda: 5,040 sectors (2 MB), model "BXHD00011", serial "Generic 1234"
hda1: 217 sectors (108 kB), Pintos OS kernel (20)
hda2: 4,096 sectors (2 MB), Pintos file system (21)
hda3: 133 sectors (66 kB), Pintos scratch (22)
filesys: using hda2
scratch: using hda3
Formatting file system...done.
Boot complete.
Extracting ustar archive from scratch device into file system...
Putting 'do-nothing' into the file system...
Erasing ustar archive...
##########
(gdb) p thread_current()
$1 = (struct thread *) 0xc000e000
(gdb) p *thread_current()
$2 = {tid = 1, status = THREAD_RUNNING, name = "main", '\000' <repeats 11 times>, stack = 0xc000edbc "\335\322\002\300\n", priority = 31, allelem = {prev = 0xc003b19c <all_list>, next = 0xc0104020},
  elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0xc010500c, magic = 3446325067}
(gdb) dumplist &all_list thread allelem
pintos-debug: dumplist #0: 0xc000e000 {tid = 1, status = THREAD_RUNNING, name = "main", '\000' <repeats 11 times>, stack = 0xc000edbc "\335\322\002\300\n", priority = 31, allelem = {
    prev = 0xc003b19c <all_list>, next = 0xc0104020}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0xc010500c, magic = 3446325067}
pintos-debug: dumplist #1: 0xc0104000 {tid = 2, status = THREAD_BLOCKED, name = "idle", '\000' <repeats 11 times>, stack = 0xc0104f14 "", priority = 0, allelem = {prev = 0xc000e020,
    next = 0xc003b1a4 <all_list+8>}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0x0, magic = 3446325067}
(gdb) p *(struct thread *) 0xc000e000
$3 = {tid = 1, status = THREAD_RUNNING, name = "main", '\000' <repeats 11 times>, stack = 0xc000edbc "\335\322\002\300\n", priority = 31, allelem = {
    prev = 0xc003b19c <all_list>, next = 0xc0104020}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0xc010500c, magic = 3446325067}
(gdb) p *(struct thread *) 0xc0104000
$4 = {tid = 2, status = THREAD_BLOCKED, name = "idle", '\000' <repeats 11 times>, stack = 0xc0104f14 "", priority = 0, allelem = {prev = 0xc000e020,
    next = 0xc003b1a4 <all_list+8>}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0x0, magic = 3446325067}

(gdb) bt
#0  process_execute (file_name=0xc0007d50 "do-nothing") at ../../userprog/process.c:57
#1  0xc0020a62 in run_task (argv=0xc003b08c <argv+12>) at ../../threads/init.c:315
#2  0xc0020ba4 in run_actions (argv=0xc003b08c <argv+12>) at ../../threads/init.c:388
#3  0xc0020421 in main () at ../../threads/init.c:136

(gdb) p thread_current()
$5 = (struct thread *) 0xc010b000
(gdb) p *thread_current()
$6 = {tid = 3, status = THREAD_RUNNING, name = "do-nothing\000\000\000\000\000", stack = 0xc010bfd4 "", priority = 31, allelem = {prev = 0xc0104020,
    next = 0xc003b1a4 <all_list+8>}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0x0, magic = 3446325067}
(gdb) dumplist &all_list thread allelem
pintos-debug: dumplist #0: 0xc000e000 {tid = 1, status = THREAD_BLOCKED, name = "main", '\000' <repeats 11 times>, stack = 0xc000ee7c "", priority = 31, allelem = {
    prev = 0xc003b19c <all_list>, next = 0xc0104020}, elem = {prev = 0xc003cbb8 <temporary+4>, next = 0xc003cbc0 <temporary+12>}, pcb = 0xc010500c, magic = 3446325067}
pintos-debug: dumplist #1: 0xc0104000 {tid = 2, status = THREAD_BLOCKED, name = "idle", '\000' <repeats 11 times>, stack = 0xc0104f14 "", priority = 0, allelem = {
    prev = 0xc000e020, next = 0xc010b020}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0x0, magic = 3446325067}
pintos-debug: dumplist #2: 0xc010b000 {tid = 3, status = THREAD_RUNNING, name = "do-nothing\000\000\000\000\000", stack = 0xc010bfd4 "", priority = 31, allelem = {
    prev = 0xc0104020, next = 0xc003b1a4 <all_list+8>}, elem = {prev = 0xc003b18c <fifo_ready_list>, next = 0xc003b194 <fifo_ready_list+8>}, pcb = 0x0, magic = 3446325067}

Breakpoint 4, start_process (file_name_=0xc010a000) at ../../userprog/process.c:102
102         success = load(file_name, &if_.eip, &if_.esp);
(gdb) p/x if_
$7 = {edi = 0x0, esi = 0x0, ebp = 0x0, esp_dummy = 0x0, ebx = 0x0, edx = 0x0, ecx = 0x0, eax = 0x0, gs = 0x23, fs = 0x23, es = 0x23, ds = 0x23, vec_no = 0x0, error_code = 0x0,
  frame_pointer = 0x0, eip = 0x0, cs = 0x1b, eflags = 0x202, esp = 0x0, ss = 0x23}
(gdb) n
106       if (!success && pcb_success) {
(gdb) p/x if_
$8 = {edi = 0x0, esi = 0x0, ebp = 0x0, esp_dummy = 0x0, ebx = 0x0, edx = 0x0, ecx = 0x0, eax = 0x0, gs = 0x23, fs = 0x23, es = 0x23, ds = 0x23, vec_no = 0x0, error_code = 0x0,
  frame_pointer = 0x0, eip = 0x804890f, cs = 0x1b, eflags = 0x202, esp = 0xc0000000, ss = 0x23}

Breakpoint 5, start_process (file_name_=0xc010a000) at ../../userprog/process.c:128
128       asm volatile("movl %0, %%esp; jmp intr_exit" : : "g"(&if_) : "memory");
(gdb) info registers
eax            0x0                 0
ecx            0x9                 9
edx            0xfffffdff          -513
ebx            0x0                 0
esp            0xc010bf38          0xc010bf38
ebp            0xc010bfc0          0xc010bfc0
esi            0x0                 0
edi            0x0                 0
eip            0xc002d609          0xc002d609 <start_process+328>
eflags         0x246               [ PF ZF IF ]
(gdb) info frame
Stack level 0, frame at 0xc010bfc8:
 eip = 0xc002d609 in start_process (../../userprog/process.c:128); saved eip = 0xc00214e1
 called by frame at 0xc010bff8
 source language c.
 Arglist at 0xc010bfc0, args: file_name_=0xc010a000
 Locals at 0xc010bfc0, Previous frame's sp is 0xc010bfc8
 Saved registers:
  ebp at 0xc010bfc0, eip at 0xc010bfc4
(gdb)  n..
64              iret
(gdb) info registers
eax            0x0                 0
ecx            0x0                 0
edx            0x0                 0
ebx            0x0                 0
esp            0xc010bf8c          0xc010bf8c
ebp            0x0                 0x0
esi            0x0                 0
edi            0x0                 0
eip            0xc0022456          0xc0022456 <intr_exit+10>
eflags         0x282               [ SF IF ]
cs             0x8                 8
ss             0x10                16
ds             0x23                35
es             0x23                35
fs             0x23                35
gs             0x23                35
(gdb) info frame
Stack level 0, frame at 0x0:
 eip = 0xc0022456 in intr_exit (../../threads/intr-stubs.S:64); saved eip = <not saved>
 Outermost frame: outermost
 source language asm.
 Arglist at unknown address.
 Locals at unknown address, Previous frame's sp in esp

(gdb) n // returned to userspace # do-nothing: exit(162)
0x0804890f in ?? ()
(gdb) info registers
eax            0x0                 0
ecx            0x0                 0
edx            0x0                 0
ebx            0x0                 0
esp            0xc0000000          0xc0000000
ebp            0x0                 0x0
esi            0x0                 0
edi            0x0                 0
eip            0x804890f           0x804890f
(gdb) info frame
Stack level 0, frame at 0x0:
 eip = 0x804890f; saved eip = <not saved>
 Outermost frame: outermost
 Arglist at unknown address.
 Locals at unknown address, Previous frame's sp in esp

(gdb) bt
#0  0x0804890f in ?? ()
(gdb) loadusersymbols tests/userprog/do-nothing
add symbol table from file "tests/userprog/do-nothing" at
        .text_addr = 0x8048094
(gdb) bt
#0  _start () at ../../lib/user/entry.c:9
(gdb) disassemble
Dump of assembler code for function _start:
=> 0x0804890f <+0>:     push   %ebp
   0x08048910 <+1>:     mov    %esp,%ebp
   0x08048912 <+3>:     sub    $0x28,%esp
   0x08048915 <+6>:     mov    %esp,%eax
   0x08048917 <+8>:     mov    %eax,-0xc(%ebp)
   0x0804891a <+11>:    mov    -0xc(%ebp),%eax
   0x0804891d <+14>:    mov    (%eax),%eax
   0x0804891f <+16>:    mov    %eax,-0x10(%ebp)
(gdb) stepi
0x08048910      9       void _start(void) {
0x08048912 in _start () at ../../lib/user/entry.c:9
9       void _start(void) {
(gdb) s..
24          exit(main(argc, argv));
(gdb) info registers
eax            0xbfffffd8          -1073741864
ecx            0x0                 0
edx            0x0                 0
ebx            0x0                 0
esp            0xbfffffd4          0xbfffffd4
ebp            0xbffffffc          0xbffffffc
esi            0x0                 0
edi            0x0                 0
eip            0x804892b           0x804892b <_start+28>
eflags         0x286               [ PF SF IF ]
(gdb) info frame
Stack level 0, frame at 0xc0000004:
 eip = 0x804892b in _start (../../lib/user/entry.c:24); saved eip = 0xf000ff53
 called by frame at 0x0
 source language c.
 Arglist at 0xbffffffc, args:
 Locals at 0xbffffffc, Previous frame's sp is 0xc0000004
 Saved registers:
  ebp at 0xbffffffc, eip at 0xc0000000
(gdb) bt
#0  _start () at ../../lib/user/entry.c:24
#1  0xf000ff53 in ?? ()
(gdb) s
main (argc=0, argv=0xbfffffd8) at ../../tests/userprog/do-nothing.c:5
5       int main(int argc UNUSED, char* argv[] UNUSED) { return 162; }
(gdb) s
exit (status=162) at ../../lib/user/syscall.c:75
74      void exit(int status) {
75        syscall1(SYS_EXIT, status);
76        NOT_REACHED();
77      }
(gdb) info registers
eax            0xa2                162
ecx            0x0                 0
edx            0x0                 0
ebx            0x0                 0
esp            0xbfffffa4          0xbfffffa4
ebp            0xbfffffcc          0xbfffffcc
esi            0x0                 0
edi            0x0                 0
eip            0x804ac1f           0x804ac1f <exit+6>
eflags         0x282               [ SF IF ]
(gdb) info frame
Stack level 0, frame at 0xbfffffd4:
 eip = 0x804ac1f in exit (../../lib/user/syscall.c:75); saved eip = 0x8048945
 called by frame at 0xc0000004
 source language c.
 Arglist at 0xbfffffcc, args: status=162
 Locals at 0xbfffffcc, Previous frame's sp is 0xbfffffd4
 Saved registers:
  ebp at 0xbfffffcc, eip at 0xbfffffd0
(gdb) bt
#0  exit (status=162) at ../../lib/user/syscall.c:75
#1  0x08048945 in _start () at ../../lib/user/entry.c:24
#2  0xf000ff53 in ?? ()
(gdb) s
intr30_stub () at ../../threads/intr-stubs.S:140
140     STUB(30, zero) STUB(31, zero) STUB(32, zero) STUB(33, zero)
(gdb) bt
#0  intr30_stub () at ../../threads/intr-stubs.S:140
#1  0x0804ac26 in exit (status=162) at ../../lib/user/syscall.c:75
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) btpagefault
#0  0x0000001b in ?? ()
#1  0x08048945 in _start () at ../../lib/user/entry.c:24
#2  0xf000ff53 in ?? ()
(gdb) s
intr_entry () at ../../threads/intr-stubs.S:21
21              pushl %ds
(gdb) s..
intr_entry () at ../../threads/intr-stubs.S:37
37              call intr_handler
(gdb) s
intr_handler (frame=0xc010bfb0) at ../../threads/interrupt.c:327
327       external = frame->vec_no >= 0x20 && frame->vec_no < 0x30;
(gdb) s..
337       handler = intr_handlers[frame->vec_no];
(gdb) p/x intr_handlers
$2 = {0xc002e91f, 0xc002e91f, 0x0, 0xc002e91f, 0xc002e91f, 0xc002e91f, 0xc002e91f, 0xc002e91f, 0x0, 0x0, 0x0, 0xc002e91f, 0xc002e91f, 0xc002e91f, 0xc002ea31, 0x0, 0xc002e91f,
  0x0, 0x0, 0xc002e91f, 0x0 <repeats 12 times>, 0xc0024aec, 0xc0024e6a, 0x0, 0x0, 0xc00259a9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00271c0, 0xc00271c0, 0xc002eb2d,
  0x0 <repeats 207 times>}
(gdb) s..
339         handler(frame);
(gdb) p/x handler
$1 = 0xc002eb2d
(gdb) s
syscall_handler (f=0xc010bfb0) at ../../userprog/syscall.c:13
13        uint32_t* args = ((uint32_t*)f->esp);
(gdb) n..
26          printf("%s: exit(%d)\n", thread_current()->pcb->process_name, args[1]);
(gdb) n
27          process_exit();
(gdb) s
process_exit () at ../../userprog/process.c:148
148       struct thread* cur = thread_current();
(gdb) n..
159       pd = cur->pcb->pagedir;
(gdb) n..
182       thread_exit();
(gdb) s
thread_exit () at ../../threads/thread.c:289
289       ASSERT(!intr_context());
(gdb) n..
297       schedule();
(gdb) s
schedule () at ../../threads/thread.c:539
539       struct thread* cur = running_thread();
(gdb) n..
548         prev = switch_threads(cur, next);
(gdb)
Remote connection closed
(gdb)  q
##########
Execution of 'do-nothing' complete.
Timer: 516 ticks
Thread: 131 idle ticks, 34 kernel ticks, 355 user ticks
hda2 (filesys): 68 reads, 270 writes
hda3 (scratch): 132 reads, 2 writes
Console: 861 characters output
Keyboard: 0 keys pressed
Exception: 0 page faults
Powering off...
========================================================================
Bochs is exiting with the following message:
[ACPI  ] ACPI control: soft power off
========================================================================
```